import assert from 'node:assert/strict';
import test from 'node:test';

import { serializeStoryBrief } from '../index.mjs';

function fullStory(overrides = {}) {
  return {
    id: 'story-1',
    epic: 'epic-1',
    description: '  Ship the story dispatch bridge.',
    acceptance_criteria: ['formats markdown', 'assigns agent'],
    files_to_modify: [
      { file: 'hive/lib/example.mjs', change: 'add helper' },
    ],
    code_examples: [
      {
        title: 'Call helper',
        file: 'hive/lib/example.mjs',
        language: 'js',
        snippet: 'await dispatchStoryToAgent(serverUrl, token, workspaceId, issueUuid, agentUuid);',
      },
    ],
    references: [
      {
        path: 'hive/lib/multica-bootstrap/index.mjs',
        relevant_excerpt: 'httpJson and cache patterns',
      },
    ],
    ...overrides,
  };
}

test('default behavior: omitted options emits no Use /codex:rescue section', () => {
  const brief = serializeStoryBrief(fullStory());
  assert.doesNotMatch(brief, /^## Use \/codex:rescue/m);
  assert.doesNotMatch(brief, /\/codex:rescue/);
});

test('default behavior: codexInstruction:false emits no Use /codex:rescue section', () => {
  const brief = serializeStoryBrief(fullStory(), { codexInstruction: false });
  assert.doesNotMatch(brief, /^## Use \/codex:rescue/m);
  assert.doesNotMatch(brief, /\/codex:rescue/);
});

test('codexInstruction:true emits Use /codex:rescue section between Goal and Acceptance Criteria', () => {
  const brief = serializeStoryBrief(fullStory(), { codexInstruction: true });
  assert.match(brief, /^## Use \/codex:rescue/m);
  assert.match(brief, /\/codex:rescue/);

  const goalIdx = brief.indexOf('## Goal');
  const codexIdx = brief.indexOf('## Use /codex:rescue');
  const acIdx = brief.indexOf('## Acceptance Criteria');
  assert.ok(goalIdx >= 0 && codexIdx > goalIdx && acIdx > codexIdx,
    `expected order Goal < Use /codex:rescue < Acceptance Criteria; got ${goalIdx}, ${codexIdx}, ${acIdx}`);
});

test('codexInstruction:true preserves all other brief sections unchanged', () => {
  const brief = serializeStoryBrief(fullStory(), { codexInstruction: true });
  assert.match(brief, /^## Goal/m);
  assert.match(brief, /^## Acceptance Criteria/m);
  assert.match(brief, /^## Files to Touch/m);
  assert.match(brief, /^## Code Examples/m);
  assert.match(brief, /^## References/m);
  assert.match(brief, /Generated by hive multica-story-dispatch/);
});

test('backward-compat: legacy single-arg callers unaffected', () => {
  const briefNoArg = serializeStoryBrief(fullStory());
  const briefEmptyArg = serializeStoryBrief(fullStory(), {});
  assert.equal(briefNoArg, briefEmptyArg);
});

// Per-persona provider combinations

function makeAgents(personaName, provider) {
  return [{ name: personaName, provider }];
}

test('combo codex+codex: provider=codex + agent_backends=codex → omit rescue section', () => {
  const brief = serializeStoryBrief(fullStory(), {
    dispatchingPersona: 'backend-developer',
    agents: makeAgents('backend-developer', 'codex'),
    agentBackends: { 'backend-developer': 'codex' },
  });
  assert.doesNotMatch(brief, /\/codex:rescue/);
});

test('combo codex+claude: provider=codex + agent_backends=claude → omit rescue section', () => {
  const brief = serializeStoryBrief(fullStory(), {
    dispatchingPersona: 'backend-developer',
    agents: makeAgents('backend-developer', 'codex'),
    agentBackends: { 'backend-developer': 'claude' },
  });
  assert.doesNotMatch(brief, /\/codex:rescue/);
});

test('combo claude+codex: provider=claude + agent_backends=codex → omit rescue section', () => {
  const brief = serializeStoryBrief(fullStory(), {
    dispatchingPersona: 'reviewer',
    agents: makeAgents('reviewer', 'claude'),
    agentBackends: { reviewer: 'codex' },
  });
  assert.doesNotMatch(brief, /\/codex:rescue/);
});

test('combo claude+claude: provider=claude + agent_backends=claude → omit rescue section', () => {
  const brief = serializeStoryBrief(fullStory(), {
    dispatchingPersona: 'reviewer',
    agents: makeAgents('reviewer', 'claude'),
    agentBackends: { reviewer: 'claude' },
  });
  assert.doesNotMatch(brief, /\/codex:rescue/);
});

test('integrationBranch: normal branch is single-quoted in rendered git commands', () => {
  const brief = serializeStoryBrief(fullStory(), { integrationBranch: 'feat/epic-1' });
  assert.match(brief, /git fetch origin 'feat\/epic-1'/);
  assert.match(brief, /git checkout 'feat\/epic-1'/);
  assert.match(brief, /git reset --hard origin\/'feat\/epic-1'/);
  assert.match(brief, /git push origin HEAD:'feat\/epic-1'/);
});

test('integrationBranch: shell metacharacters are neutralized by quoting', () => {
  const brief = serializeStoryBrief(fullStory(), { integrationBranch: 'feat/x;$(touch pwned)' });
  // The branch must appear only inside single quotes — never as bare, executable text.
  assert.match(brief, /git fetch origin 'feat\/x;\$\(touch pwned\)'/);
  assert.doesNotMatch(brief, /git fetch origin feat\/x;\$\(touch pwned\)/);
});
